### ISSUE TITLE
연구주제 선정

### ISSUE THREAD

**Issue by being0606** [being0606/LesionDetector#2]
1. 모델 간 비교 : 1-stage(YOLO based) vs 2-stage(CNN based)
2. 데이터셋 간 비교 : Argmentated vs Vanila(Robust?)
3. 학습시간과 컴퓨팅버짓에 대한 다양한 시도 : Pre-trained(or Transfer) learning vs Vanila(Robust?)

**Comment by being0606** [comment]
2.1. 데이터셋 간 비교하기 위한 모델의 고정
-> SOTA  vs  Off-the-shelf model  vs  baseline

**Comment by hyeseon-cpu** [comment]
### **확인했습니다~******
